name: ecommerce
description: ecommerce
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_swiper_null_safety: ^1.0.2
  cupertino_icons:
  flutter_slidable:
  get:
  http:
  cached_network_image:
  image_picker:
  show_up_animation:
  auto_animated:
  flutter_polyline_points:
  google_maps_flutter:
  geolocator:
  navigator:
  fluttertoast:
  animated_splash_screen:
  introduction_screen:
  flutter_svg:
  shimmer:
  sizer:
  smooth_page_indicator:
  consumer:
  dio:
  modal_progress_hud_nsn:
  flutter_spinkit:
  google_fonts:
  country_code_picker:
  location:
  otp_text_field:
  provider:
  bottom_navy_bar:
  easy_localization:
  hexcolor:
  connectivity:
  flutter_bloc:
  bloc:
  modal_progress_hud:
  pixel_perfect:
  hexcore:
  expandable:
  shared_preferences:
  badges:
  font_awesome_flutter:
  fluttericon:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo/Cairo-Bold.ttf
          weight: 700
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
